# BUATLAH PROGRAM YANG SAAT DIJALANKAN AKAN
# MENCETAK TULISAN SEPERTI YANG ADA DI BAWAH INI
#    *
#   ***
#  *****
# *******
#  *****
#   ***
#    *
# MANFAATKAN PERULANGAN SERTA PERCABANGAN YANG SUDAH DIAJARKAN
# CONTOH CODE SEPERTI YANG ADA DI FILE bintang.py
# 
